Repository ZB-Online/TeamFinder, pull requests merged in 2021-12, with the labels that each got.

#9 Feature/8 api
  README.md
  babel.config.json
  package-lock.json
  package.json
  server.js
  src/model/Comment.js
  src/model/Posting.js
  src/model/User.js
  src/router/api.js
  src/router/root.js
Labels: enhancement

#12 Feature/3 home layout
  public/Home/filter.js
  public/Home/posting.js
  public/app.js
  public/assets/img/filter/농구.png
  public/assets/img/filter/당구.png
  public/assets/img/filter/런닝.png
  public/assets/img/filter/배드민턴.png
  public/assets/img/filter/볼링.png
  public/assets/img/filter/야구.png
  public/assets/img/filter/축구.png
  public/assets/img/user.png
  public/css/reset.css
  public/css/style.css
  public/dummy/data.js
  public/index.html
Labels: enhancement

#18 Feature/5 write page
  public/utils/date.js
  public/writing/css/writing.css
  public/writing/writing.html
  public/writing/writing.js
Labels: enhancement

#19 Feature/16 filter posts
  public/Home/filter.js
  public/Home/posting.js
  public/app.js
  public/css/style.css
  public/dummy/data.js
  public/index.html
  public/page/comment/comment.css
  public/page/comment/comment.html
  public/page/comment/comment.js
  public/page/comment/temp.css
  public/page/main/filter.js
  public/page/main/post.js
  public/page/writing/writing.css
  public/page/writing/writing.html
  public/page/writing/writing.js
  public/store/createStore.js
  public/store/filter.js
  src/router/api.js
Labels: enhancement

#21 Feature/10 comment
  public/comment/comment.html
  public/comment/css/comment.css
  public/comment/css/temp.css
  public/comment/js/app.js
  public/comment/js/comment.js
  public/comment/js/render.js
  public/page/comment/comment.js
  public/utils/date.js
  src/router/api.js
Labels: enhancement

#26 Chore: axios
  package-lock.json
  package.json
Labels: config package

#24 Feature/20 detail page
  .eslintrc.json
  public/comment/css/comment.css
  public/comment/css/temp.css
  public/comment/js/app.js
  public/comment/js/comment.js
  public/comment/js/render.js
  public/css/reset.css
  public/detail/comment.html
  public/detail/css/comment.css
  public/detail/css/post.css
  public/detail/js/app.js
  public/detail/js/post.js
  public/detail/js/render.js
  public/detail/postDetail.html
  public/page/main/post.js
  public/page/writing/writing.html
  public/page/writing/writing.js
  src/model/Comment.js
  src/model/Post.js
  src/router/api.js
Labels: enhancement

#35 Feature/28 routing
  .eslintrc.json
  .prettierrc.json
  package-lock.json
  package.json
  public/api/axios.js
  public/app.js
  public/comment/comment.html
  public/comment/css/temp.css
  public/comment/js/app.js
  public/component/App.js
  public/component/Common/Header.js
  public/component/Common/event/addHeaderEvent.js
  public/component/Home/PostList.js
  public/component/Home/event/addFilter.js
  public/component/Home/event/addPostListEvent.js
  public/component/Home/homeUtils/filter.js
  public/component/Post/Comment.js
  public/component/Post/event/addCommentEvent.js
  public/component/Post/postUtils/comment.js
  public/component/Post/postUtils/fetchComment.js
  public/component/Writing/Writing.js
  public/component/Writing/event/addWritingEvent.js
  public/css/comment.css
  public/css/reset.css
  public/css/style.css
  public/css/writing.css
  public/index.html
  public/index.js
  public/page/main/filter.js
  public/page/main/post.js
  public/page/writing/writing.html
  public/page/writing/writing.js
  public/store/filter.js
  public/utils/renderPost.js
  server.js
  src/model/Comment.js
  src/model/Posting.js
  src/model/User.js
  src/router/api.js
  src/router/root.js
Labels: bug, enhancement

#41 Issue/40 spa reload
  public/component/App.js
  public/component/Common/event/addHeaderEvent.js
  public/component/Home/event/addPostListEvent.js
  public/component/Post/Comment.js
  public/component/Writing/Writing.js
  server.js
Labels: bug

#46 Feature/45 deletion routing
  .eslintrc.json
  public/component/App.js
  public/component/Common/event/addHeaderEvent.js
  public/component/Home/Main.js
  public/component/Home/event/addPostListEvent.js
  public/component/Post/PostDetail.js
  public/component/Post/event/addPostDetailEvent.js
  public/component/Post/postUtils/renderPost.js
  public/component/Writing/Writing.js
  public/component/Writing/event/addWritingEvent.js
  public/page/main/post.js
  public/store/post.js
  test/test.js
Labels: enhancement

#38 Feature/33 setting page
  public/api/axios.js
  public/component/App.js
  public/component/Common/Header.js
  public/component/Common/event/addHeaderEvent.js
  public/component/Home/PostList.js
  public/component/Setting/Setting.js
  public/component/Setting/event/addSettingEvent.js
  public/component/Writing/event/addWritingEvent.js
  public/css/setting.css
  public/css/writing.css
  public/index.html
  public/utils/renderPost.js
  public/utils/toaster.js
  src/router/api.js
  src/router/root.js
Labels: enhancement

#43 Feature/42 writing page spa
  public/component/Writing/Writing.js
  public/component/Writing/event/addWritingEvent.js
  public/css/style.css
  public/css/writing.css
Labels: enhancement

#34 Feature/2 new sign in branch
  package-lock.json
  public/component/Common/Header.js
  public/css/style.css
  public/page/main/login.js
  server.js
  src/model/Comment.js
  src/model/Posting.js
  src/model/User.js
  src/router/api.js
  src/router/root.js
Labels: enhancement

#39 Feature/36 edit page
  .eslintrc.json
  public/component/App.js
  public/component/Common/event/addHeaderEvent.js
  public/component/Home/Main.js
  public/component/Home/event/addPostListEvent.js
  public/component/Post/Comment.js
  public/component/Post/PostDetail.js
  public/component/Post/event/addCommentEvent.js
  public/component/Post/event/addPostDetailEvent.js
  public/component/Post/postUtils/comment.js
  public/component/Post/postUtils/fetchComment.js
  public/component/Post/postUtils/renderPost.js
  public/component/Setting/Setting.js
  public/component/Setting/event/addSettingEvent.js
  public/component/Writing/Writing.js
  public/component/Writing/event/addWritingEvent.js
  public/css/comment.css
  public/css/post.css
  public/css/reset.css
  public/css/style.css
  public/index.html
  public/page/main/post.js
  public/store/post.js
  public/utils/renderPost.js
  server.js
  src/model/Comment.js
  src/model/Post.js
  src/model/Posting.js
  src/router/api.js
  src/router/root.js
Labels: enhancement

#49 Feature/47-headerIssue
  public/component/Setting/event/addSettingEvent.js
  public/css/post.css
  public/css/style.css
  public/utils/toaster.js
Labels: bug

#54 Issue/53 main
  public/component/Common/Header.js
  public/component/Common/event/addHeaderEvent.js
  public/css/style.css
  public/utils/renderPost.js
  src/router/api.js
  src/router/data.js
Labels: bug, enhancement

#56 Feat: popular filter
  public/component/Home/event/addFilter.js
  public/utils/renderPost.js
Labels: enhancement
